# -*- mode: conf-toml; -*-
# sm2.toml 202402010647
[MrState]

  imagedirs=[
   "/data/ackley/PART4/papers/ALIFE23/talk",
   "/data/ackley/AV/STREAMDECK/ICONS/MINE/OBS",
   "/data/ackley/AV/STREAMDECK/ICONS/72/Large",
   "/data/ackley/AV/OBS2021/assets/images/",
   "/data/ackley/PART4/images",
   "~/Pictures",
   "."]
  bindirs=[
   "/data/ackley/AV/OBS2021/assets/obs-cli",
   ""                           # include default path
   ]

[config]
  worldSDF="world.sdf"
  planeURDF="plane.urdf"
  robotURDF="genRobot.urdf"

[term.BVCODE]
  type=sensor
  name='Beevee Driving Code'
  # 0: 2A, 1: 2B, 2: 3A, 3: 3B
  value=2
  tile=0

[term.SLFL]
  type=sensor
  name='Left Front Yellow Detector'
  tile=0

[term.SRFL]
  type=sensor
  name='Right Front Yellow Detector'
  tile=0

[term.MRR]
  type=motor
  joint=base_to_rwheel
  name='Right Rear Motor'
  tile=0

[term.MLR]
  type=motor
  joint=base_to_lwheel
  name='Left Rear Motor'
  tile=0



  